# Generated by Django 5.2 on 2025-05-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('compressor', '0001_initial'), ('compressor', '0002_alter_video_compression'), ('compressor', '0003_remove_video_compression_video_compression_meta'), ('compressor', '0004_remove_video_compression_meta_alter_video_options_and_more'), ('compressor', '0005_video_is_compressed')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('bandwidth', models.IntegerField(default=None, null=True)),
                ('crf', models.IntegerField(default=None, null=True)),
                ('height', models.IntegerField(default=None, null=True)),
                ('width', models.IntegerField(default=None, null=True)),
                ('is_compressed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
