# Generated by Django 5.2 on 2025-05-28 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0001_squashed_0005_video_is_compressed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('filename',)},
        ),
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='filename',
        ),
        migrations.AddField(
            model_name='video',
            name='original_filename',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='psnr_mean',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='ssim_mean',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='vmaf_mean',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='FrameMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('frame_type', models.CharField(choices=[('I', 'I-frame (Intra frame, keyframe)'), ('P', 'P-frame (Predictive frame)'), ('B', 'B-frame (Bidirectional frame)')], max_length=1)),
                ('vmaf_score', models.FloatField(default=0.0)),
                ('psnr_score', models.FloatField(default=0.0)),
                ('ssim_score', models.FloatField(default=0.0)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compressor.video')),
            ],
            options={
                'unique_together': {('video', 'frame_number')},
            },
        ),
    ]
