# Generated by Django 5.2 on 2025-05-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0006_alter_video_options_rename_name_video_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='framemetadata',
            name='pts_time',
            field=models.FloatField(default=None, null=True),
        ),
    ]
