# Generated by Django 5.2 on 2025-05-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0007_framemetadata_pts_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='framemetadata',
            name='image_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
