# Generated by Django 5.2 on 2025-05-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0008_framemetadata_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='framemetadata',
            old_name='frame_type',
            new_name='type',
        ),
    ]
