# Generated by Django 5.2 on 2025-05-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0010_remove_video_original_filename_video_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='framemetadata',
            name='pkt_size',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
