# Generated by Django 5.2.1 on 2025-09-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('compressor', '0013_video_original_filename_video_title'), ('compressor', '0014_video_aq_mode_video_aq_strength_video_b_frames'), ('compressor', '0015_rename_b_frames_video_bf'), ('compressor', '0016_video_preset'), ('compressor', '0017_alter_video_aq_strength'), ('compressor', '0018_alter_video_bf'), ('compressor', '0019_video_size'), ('compressor', '0020_video_frames_extraction_completed_and_more')]

    dependencies = [
        ('compressor', '0012_video_gop_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='original_filename',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='Unknown Video', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='aq_mode',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='preset',
            field=models.CharField(default='medium', max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='aq_strength',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='bf',
            field=models.CharField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='size',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='frames_extraction_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='frames_extraction_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
