# Generated by Django 5.2.3 on 2025-07-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0012_video_gop_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='original_filename',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='Unknown Video', max_length=255),
        ),
    ]
