# Generated by Django 5.2.3 on 2025-07-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0013_video_original_filename_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='aq_mode',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='aq_strength',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='b_frames',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
