# Generated by Django 5.2.3 on 2025-07-02 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0014_video_aq_mode_video_aq_strength_video_b_frames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='b_frames',
            new_name='bf',
        ),
    ]
