# Generated by Django 5.2.3 on 2025-07-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0015_rename_b_frames_video_bf'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preset',
            field=models.CharField(default='medium', max_length=50),
        ),
    ]
