# Generated by Django 5.2.3 on 2025-07-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0016_video_preset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='aq_strength',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=3, null=True),
        ),
    ]
