# Generated by Django 5.2.3 on 2025-07-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0017_alter_video_aq_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='bf',
            field=models.CharField(default=None, null=True),
        ),
    ]
