# Generated by Django 5.2.3 on 2025-07-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0018_alter_video_bf'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='size',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
