# Generated by Django 5.2.3 on 2025-07-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0019_video_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='frames_extraction_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='frames_extraction_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
