# Generated by Django 5.2.7 on 2025-10-17 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0013_video_original_filename_video_title_squashed_0020_video_frames_extraction_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vmaf_mean', models.FloatField(default=None, null=True)),
                ('psnr_mean', models.FloatField(default=None, null=True)),
                ('ssim_mean', models.FloatField(default=None, null=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='compressor.video')),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='psnr_mean',
        ),
        migrations.RemoveField(
            model_name='video',
            name='ssim_mean',
        ),
        migrations.RemoveField(
            model_name='video',
            name='vmaf_mean',
        ),
    ]
