# Generated by Django 5.2.7 on 2025-10-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0021_remove_video_psnr_mean_remove_video_ssim_mean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='psnr_mean',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='ssim_mean',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='vmaf_mean',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='VideoMetrics',
        ),
    ]
