# Generated by Django 5.2.7 on 2025-11-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0023_remove_video_psnr_mean_remove_video_ssim_mean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='macroblocks_extraction_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='macroblocks_extraction_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
