# Generated by Django 5.2.8 on 2025-11-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0024_video_macroblocks_extraction_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='framemetadata',
            name='dts_time',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='framemetadata',
            name='scene_score',
            field=models.FloatField(default=0.0),
        ),
    ]
