# Generated by Django 5.2.9 on 2025-12-15 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('compressor', '0026_quiz_quizquestion'), ('compressor', '0027_quiz_video'), ('compressor', '0028_remove_quiz_video_quiz_video_filename'), ('compressor', '0029_quizquestion_image'), ('compressor', '0030_quiz_assets_location'), ('compressor', '0031_remove_quizquestion_correct_answers'), ('compressor', '0032_quiz_archive_location')]

    dependencies = [
        ('compressor', '0025_framemetadata_dts_time_framemetadata_scene_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('video_filename', models.CharField(default=None, max_length=255, null=True)),
                ('assets_location', models.CharField(default=None, max_length=255, null=True)),
                ('archive_location', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answers', models.JSONField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compressor.quiz')),
                ('image', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
