# Generated by Django 5.2.9 on 2025-12-28 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0025_video_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='created_at',
        ),
    ]
