# Generated by Django 5.2.9 on 2025-12-12 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0026_quiz_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='video',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='compressor.video'),
        ),
    ]
