# Generated by Django 5.2.9 on 2025-12-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0027_quiz_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='video',
        ),
        migrations.AddField(
            model_name='quiz',
            name='video_filename',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
