# Generated by Django 5.2.9 on 2025-12-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0028_remove_quiz_video_quiz_video_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='image',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
