# Generated by Django 5.2.9 on 2025-12-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0029_quizquestion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='assets_location',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
