# Generated by Django 5.2.9 on 2025-12-14 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0030_quiz_assets_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='correct_answers',
        ),
    ]
