# Generated by Django 5.2.9 on 2025-12-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0031_remove_quizquestion_correct_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='archive_location',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
