# Generated by Django 5.2.9 on 2025-12-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0026_quiz_quizquestion_squashed_0032_quiz_archive_location'),
        ('compressor', '0027_video_created_at'),
    ]

    operations = [
    ]
